# Order properties config : https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config

# Configuration globale sur l'ensemble des environnements
spring:
  application:
    name: Heritage
  datasource:
    driver-class-name: 
    name: heritage
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/heritage?currentSchema=heritage
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate: DEBUG
      hibernate.SQL: DEBUG
      # hibernate.type.descriptor.sql.BasicBinder: TRACE
      # hibernate.engine.transaction.internal.TransactionImpl: DEBUG
server:
  servlet:
    session:
      cookie:
        secure: false
server:
  port: 8082
